server:
    port: 8181

feign:
    httpclient:
        disableSslValidation: true
    client:
      config:
        default:
          connectTimeout: 5000
          readTimeout: 5000
          loggerLevel: basic
    nominatim:
        name: openatim
        url: https://nominatim.openstreetmap.org
    openweather:
        name: openweather
        key: f4b84caaa15a14077daa494326b1163e
